server {
  listen 80;
  root /usr/share/nginx/html/browser;
  index index.html;

  add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;

  location /api/ {
    proxy_pass http://backend:8080/api/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
