INSERT INTO citizens (run, full_name, email, phone, preferred_channel) VALUES ('12.345.678-9', 'Benjamin Cruzado', 'benjamin@example.local', '+56 9 0000 0000', 'email');
INSERT INTO institutions (code, name, service_level) VALUES ('REGCIVIL', 'Registro Civil', 'critico'), ('MINSEGPRES', 'MINSEGPRES', 'alto');
INSERT INTO service_categories (code, name, display_order) VALUES ('ID', 'Identidad digital', 1), ('DDU', 'Domicilio digital', 2), ('CERT', 'Certificados', 3);
INSERT INTO services (code, name, institution, available, channel) VALUES ('SVC-DDU', 'Actualizar domicilio digital', 'MINSEGPRES', true, 'web'), ('SVC-CERT', 'Solicitar certificado ciudadano', 'Registro Civil', true, 'web');
INSERT INTO procedures (citizen_id, service_id, name, status, owner) SELECT c.id, s.id, s.name, 'en curso', s.institution FROM citizens c CROSS JOIN services s WHERE c.run='12.345.678-9' LIMIT 2;
INSERT INTO procedure_steps (procedure_id, step_order, title, status, due_at) SELECT id, 1, 'Recepcion de solicitud', 'completado', current_date + 1 FROM procedures;
INSERT INTO notifications (citizen_id, procedure_id, subject, priority, channel) SELECT c.id, p.id, 'Vencimiento de tramite', 'alta', 'portal' FROM citizens c JOIN procedures p ON p.citizen_id=c.id LIMIT 1;
INSERT INTO sessions (citizen_id, device, location, active, trusted) SELECT id, 'Notebook', 'Santiago', true, true FROM citizens WHERE run='12.345.678-9';
INSERT INTO consents (citizen_id, institution, data_scope, status, expires_at) SELECT id, 'Registro Civil', 'Identidad', 'vigente', '2026-12-31' FROM citizens WHERE run='12.345.678-9';
INSERT INTO cases (citizen_id, procedure_id, status, responsible) SELECT c.id, p.id, 'en revision', 'Mesa ciudadana' FROM citizens c JOIN procedures p ON p.citizen_id=c.id LIMIT 1;
INSERT INTO digital_addresses (citizen_id, address_line, comuna, status) SELECT id, 'Avenida Demo 123', 'Santiago', 'vigente' FROM citizens WHERE run='12.345.678-9';
INSERT INTO address_history (citizen_id, address_line, source) SELECT id, 'Avenida Demo 123', 'ciudadano' FROM citizens WHERE run='12.345.678-9';
INSERT INTO notification_preferences (citizen_id, channel, quiet_hours, min_priority) SELECT id, 'email', '22:00-08:00', 'media' FROM citizens WHERE run='12.345.678-9';
INSERT INTO support_tickets (citizen_id, topic, channel, status) SELECT id, 'Clave bloqueada', 'chat', 'abierto' FROM citizens WHERE run='12.345.678-9';
INSERT INTO faq_entries (question, category, answer, helpful_count) VALUES ('Como cambio mi domicilio digital?', 'DDU', 'Ingresa a Domicilio Digital y adjunta evidencia.', 12);
INSERT INTO integration_status (service_name, status, latency_ms) VALUES ('ClaveUnica', 'operativo', 120), ('DDU', 'degradado', 650);
INSERT INTO business_rules (rule_code, module, description) VALUES ('RN-TRAMITE-001', 'procedures', 'Todo tramite debe registrar responsable y estado.'), ('RN-CONSENT-001', 'consents', 'Toda revocacion debe quedar en historial.');
INSERT INTO validation_rules (rule_code, field_name, expression, message) VALUES ('CH-RUN-001', 'run', 'not blank and format chileno', 'RUN obligatorio'), ('CH-EMAIL-001', 'email', 'contains @', 'Correo invalido');
INSERT INTO roles (code, name, description) VALUES ('CITIZEN', 'Ciudadano', 'Usuario autenticado del portal');
INSERT INTO permissions (code, description, resource) VALUES ('PROCEDURE_WRITE', 'Crear y actualizar tramites propios', 'procedures');
INSERT INTO user_roles (citizen_id, role_id) SELECT c.id, r.id FROM citizens c CROSS JOIN roles r WHERE c.run='12.345.678-9' AND r.code='CITIZEN';
INSERT INTO audit_events (citizen_id, event_type, detail) SELECT id, 'LOGIN_OK', 'Sesion inicial de datos semilla' FROM citizens WHERE run='12.345.678-9';
