import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'portal/dashboard', pathMatch: 'full' },
  { path: 'seguridad/auth-login', loadComponent: () => import('./pages/screen-01.component').then(m => m.Screen01Component) },
  { path: 'seguridad/auth-recovery', loadComponent: () => import('./pages/screen-02.component').then(m => m.Screen02Component) },
  { path: 'portal/dashboard', loadComponent: () => import('./pages/screen-03.component').then(m => m.Screen03Component) },
  { path: 'portal/catalog', loadComponent: () => import('./pages/screen-04.component').then(m => m.Screen04Component) },
  { path: 'portal/service-detail', loadComponent: () => import('./pages/screen-05.component').then(m => m.Screen05Component) },
  { path: 'perfil/profile', loadComponent: () => import('./pages/screen-06.component').then(m => m.Screen06Component) },
  { path: 'perfil/contact', loadComponent: () => import('./pages/screen-07.component').then(m => m.Screen07Component) },
  { path: 'perfil/privacy', loadComponent: () => import('./pages/screen-08.component').then(m => m.Screen08Component) },
  { path: 'seguridad/sessions', loadComponent: () => import('./pages/screen-09.component').then(m => m.Screen09Component) },
  { path: 'seguridad/mfa', loadComponent: () => import('./pages/screen-10.component').then(m => m.Screen10Component) },
  { path: 'ddu/address-current', loadComponent: () => import('./pages/screen-11.component').then(m => m.Screen11Component) },
  { path: 'ddu/address-verify', loadComponent: () => import('./pages/screen-12.component').then(m => m.Screen12Component) },
  { path: 'ddu/address-history', loadComponent: () => import('./pages/screen-13.component').then(m => m.Screen13Component) },
  { path: 'notificaciones/inbox', loadComponent: () => import('./pages/screen-14.component').then(m => m.Screen14Component) },
  { path: 'notificaciones/message-detail', loadComponent: () => import('./pages/screen-15.component').then(m => m.Screen15Component) },
  { path: 'notificaciones/notification-settings', loadComponent: () => import('./pages/screen-16.component').then(m => m.Screen16Component) },
  { path: 'autorizaciones/consent-list', loadComponent: () => import('./pages/screen-17.component').then(m => m.Screen17Component) },
  { path: 'autorizaciones/consent-request', loadComponent: () => import('./pages/screen-18.component').then(m => m.Screen18Component) },
  { path: 'autorizaciones/consent-history', loadComponent: () => import('./pages/screen-19.component').then(m => m.Screen19Component) },
  { path: 'expedientes/case-board', loadComponent: () => import('./pages/screen-20.component').then(m => m.Screen20Component) },
  { path: 'expedientes/case-detail', loadComponent: () => import('./pages/screen-21.component').then(m => m.Screen21Component) },
  { path: 'expedientes/case-timeline', loadComponent: () => import('./pages/screen-22.component').then(m => m.Screen22Component) },
  { path: 'ayuda/support-home', loadComponent: () => import('./pages/screen-23.component').then(m => m.Screen23Component) },
  { path: 'ayuda/faq', loadComponent: () => import('./pages/screen-24.component').then(m => m.Screen24Component) },
  { path: 'ayuda/ticket-detail', loadComponent: () => import('./pages/screen-25.component').then(m => m.Screen25Component) },
  { path: 'auditoria/access-log', loadComponent: () => import('./pages/screen-26.component').then(m => m.Screen26Component) },
  { path: 'auditoria/data-changes', loadComponent: () => import('./pages/screen-27.component').then(m => m.Screen27Component) },
  { path: 'auditoria/audit-export', loadComponent: () => import('./pages/screen-28.component').then(m => m.Screen28Component) },
  { path: 'portal/integration-status', loadComponent: () => import('./pages/screen-29.component').then(m => m.Screen29Component) },
  { path: 'auditoria/compliance', loadComponent: () => import('./pages/screen-30.component').then(m => m.Screen30Component) },
];
