import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';

const schema = await readFile(new URL('../database/schema.sql', import.meta.url), 'utf8');
const apiCatalog = JSON.parse(await readFile(new URL('../data/api-catalog.json', import.meta.url), 'utf8'));
const traceability = JSON.parse(await readFile(new URL('../data/traceability-matrix.json', import.meta.url), 'utf8'));
const requirementsModel = JSON.parse(await readFile(new URL('../data/requirements-model.json', import.meta.url), 'utf8'));
const compose = await readFile(new URL('../docker-compose.yml', import.meta.url), 'utf8');
const routes = await readFile(new URL('../frontend/src/app/app.routes.ts', import.meta.url), 'utf8');
const controller = await readFile(new URL('../backend/src/main/java/cl/benjamin/claveunica/controller/PortalController.java', import.meta.url), 'utf8');
const service = await readFile(new URL('../backend/src/main/java/cl/benjamin/claveunica/service/PortalWorkflowService.java', import.meta.url), 'utf8');
const integrationTest = await readFile(new URL('../backend/src/test/java/cl/benjamin/claveunica/PortalWorkflowServiceTest.java', import.meta.url), 'utf8');
const migration = await readFile(new URL('../backend/src/main/resources/db/migration/V1__init_claveunica_domain.sql', import.meta.url), 'utf8');
const openapi = await readFile(new URL('../data/openapi.yaml', import.meta.url), 'utf8');
const featureApi = await readFile(new URL('../frontend/src/app/services/feature-api.service.ts', import.meta.url), 'utf8');
const portalApi = await readFile(new URL('../frontend/src/app/services/portal-api.service.ts', import.meta.url), 'utf8');
const pageFiles = await readdir(new URL('../frontend/src/app/pages/', import.meta.url));
const featureDirs = await readdir(new URL('../frontend/src/app/features/', import.meta.url));
const htmlFiles = pageFiles.filter(name => name.endsWith('.html'));
const htmlBodies = await Promise.all(htmlFiles.map(name => readFile(new URL(`../frontend/src/app/pages/${name}`, import.meta.url), 'utf8')));
const uniqueHtml = new Set(htmlBodies);

assert.equal((schema.match(/CREATE TABLE/g) || []).length, 40, 'debe generar 40 tablas PostgreSQL');
assert.equal(pageFiles.filter(name => name.endsWith('.ts')).length, 30, 'debe generar 30 componentes Angular');
assert.ok((controller.match(/Mapping\("/g) || []).length >= 40, 'debe generar al menos 40 endpoints Spring');
assert.ok(uniqueHtml.size >= 20, 'las pantallas no pueden compartir una unica plantilla HTML');
assert.match(controller, /JdbcTemplate/);
assert.match(controller, /PortalWorkflowService/);
assert.match(controller, /@Valid/);
assert.match(service, /@Transactional/);
assert.match(service, /jdbc\.update/);
assert.match(integrationTest, /Testcontainers/);
assert.match(integrationTest, /createProcedurePersistsAndUpdatesDashboard/);
assert.match(migration, /CREATE TABLE citizens/);
assert.match(openapi, /openapi: 3\.1\.0/);
assert.match(openapi, /\/api\/v1\/procedures/);
assert.match(featureApi, /runFeatureAction/);
assert.match(featureApi, /\/api\/v1\/digital-addresses/);
assert.match(portalApi, /rowsForFeature/);
assert.match(portalApi, /statusMessageForFeature/);
assert.ok(featureDirs.length >= 6, 'debe organizar frontend por features de dominio');
assert.ok(apiCatalog.endpoints.filter(endpoint => endpoint.mutates).length >= 12, 'debe tener flujos mutantes reales');
assert.ok(traceability.length >= 30, 'debe existir trazabilidad interna requisito-pantalla-accion-endpoint-tabla-test');
assert.equal(traceability.every(item => item.ui_visibility === 'internal_only'), true, 'la trazabilidad debe ser interna');
assert.equal(requirementsModel.coverage_policy.frontend_must_not_render_requirement_ids, true, 'los IDs de requisitos no se renderizan');
assert.ok(apiCatalog.endpoints.some(endpoint => endpoint.path === '/api/v1/procedures' && endpoint.method === 'POST'));
assert.ok(apiCatalog.endpoints.some(endpoint => endpoint.path === '/api/v1/consents/{id}/revoke'));
assert.doesNotMatch(controller, /endpoint\d+\(\).*status/);
assert.doesNotMatch(schema, /metadata JSONB NOT NULL DEFAULT '\{\}'/);
assert.match(schema, /CHECK \(status IN/);
assert.match(schema, /CREATE INDEX/);
assert.match(compose, /postgres:/);
assert.match(compose, /backend:/);
assert.match(compose, /frontend:/);
assert.match(routes, /loadComponent/);
const frontendText = `${featureApi}\n${portalApi}\n${htmlBodies.join('\n')}`;
assert.doesNotMatch(frontendText, /<h2>Validaciones<\/h2>|Actividad reciente|implementa campos|ejecutado desde Angular|screen\.records/);
assert.doesNotMatch(frontendText, /\b(CU|FUN|FT|RN|CH|EX|ACT|REQ)_[A-Z0-9_]*\b|traceability|trazabilidad/i);
assert.doesNotMatch(featureApi, /\/api\/v1\/actions/);
console.log('smoke ok: app funcional local con UI diferenciada, SQL de dominio y API persistente');
