CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE citizens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), run VARCHAR(12) UNIQUE NOT NULL, full_name VARCHAR(160) NOT NULL, email VARCHAR(160) NOT NULL, phone VARCHAR(32), preferred_channel VARCHAR(32) NOT NULL DEFAULT 'email', created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE credentials (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), provider VARCHAR(80) NOT NULL, assurance_level VARCHAR(40) NOT NULL, locked BOOLEAN NOT NULL DEFAULT false, last_login TIMESTAMP);
CREATE TABLE mfa_methods (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), method VARCHAR(60) NOT NULL, status VARCHAR(40) NOT NULL, backup_enabled BOOLEAN NOT NULL DEFAULT false, updated_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), device VARCHAR(100) NOT NULL, location VARCHAR(100), active BOOLEAN NOT NULL DEFAULT true, trusted BOOLEAN NOT NULL DEFAULT false, last_seen TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE services (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(180) NOT NULL, institution VARCHAR(140) NOT NULL, available BOOLEAN NOT NULL DEFAULT true, channel VARCHAR(40) NOT NULL);
CREATE TABLE procedures (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), service_id UUID REFERENCES services(id), name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, owner VARCHAR(120) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE procedure_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), procedure_id UUID REFERENCES procedures(id), step_order INTEGER NOT NULL, title VARCHAR(160) NOT NULL, status VARCHAR(40) NOT NULL, due_at DATE);
CREATE TABLE digital_addresses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), address_line VARCHAR(220) NOT NULL, comuna VARCHAR(120) NOT NULL, status VARCHAR(40) NOT NULL, verified_at TIMESTAMP);
CREATE TABLE address_evidence (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), address_id UUID REFERENCES digital_addresses(id), evidence_type VARCHAR(80) NOT NULL, issuer VARCHAR(120) NOT NULL, result VARCHAR(40) NOT NULL, uploaded_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE address_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), address_line VARCHAR(220) NOT NULL, source VARCHAR(80) NOT NULL, changed_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), procedure_id UUID REFERENCES procedures(id), subject VARCHAR(180) NOT NULL, priority VARCHAR(24) NOT NULL, channel VARCHAR(40) NOT NULL DEFAULT 'portal', read_at TIMESTAMP);
CREATE TABLE notification_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), channel VARCHAR(40) NOT NULL, quiet_hours VARCHAR(40), min_priority VARCHAR(24) NOT NULL DEFAULT 'media');
CREATE TABLE message_attachments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), notification_id UUID REFERENCES notifications(id), file_name VARCHAR(180) NOT NULL, mime_type VARCHAR(80) NOT NULL, checksum VARCHAR(120) NOT NULL);
CREATE TABLE consents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), institution VARCHAR(140) NOT NULL, data_scope VARCHAR(140) NOT NULL, status VARCHAR(40) NOT NULL, expires_at DATE);
CREATE TABLE consent_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), requester VARCHAR(140) NOT NULL, purpose TEXT NOT NULL, duration_days INTEGER NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'pendiente');
CREATE TABLE consent_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), consent_id UUID REFERENCES consents(id), action VARCHAR(60) NOT NULL, actor VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE cases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), procedure_id UUID REFERENCES procedures(id), status VARCHAR(40) NOT NULL, responsible VARCHAR(120), priority VARCHAR(24) NOT NULL DEFAULT 'media');
CREATE TABLE case_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), case_id UUID REFERENCES cases(id), event_type VARCHAR(80) NOT NULL, detail TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE case_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), case_id UUID REFERENCES cases(id), document_name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, uploaded_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE support_tickets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), topic VARCHAR(160) NOT NULL, channel VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'abierto', updated_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE support_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id UUID REFERENCES support_tickets(id), author VARCHAR(80) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE faq_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), question VARCHAR(220) NOT NULL, category VARCHAR(80) NOT NULL, answer TEXT NOT NULL, helpful_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE audit_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), event_type VARCHAR(80) NOT NULL, detail TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE audit_exports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), requested_by UUID REFERENCES citizens(id), format VARCHAR(20) NOT NULL, range_label VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'pendiente', created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE integration_status (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_name VARCHAR(120) NOT NULL, status VARCHAR(40) NOT NULL, latency_ms INTEGER NOT NULL, checked_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE security_alerts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), severity VARCHAR(24) NOT NULL, title VARCHAR(160) NOT NULL, resolved BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE trusted_devices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), device VARCHAR(100) NOT NULL, fingerprint VARCHAR(120) NOT NULL, trusted_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE profile_changes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), field_name VARCHAR(80) NOT NULL, old_value TEXT, new_value TEXT, changed_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE contact_channels (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), channel VARCHAR(40) NOT NULL, value VARCHAR(160) NOT NULL, verified BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE privacy_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), preference_key VARCHAR(80) NOT NULL, preference_value VARCHAR(120) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE institutions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(180) NOT NULL, service_level VARCHAR(40) NOT NULL);
CREATE TABLE service_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL, display_order INTEGER NOT NULL);
CREATE TABLE favorites (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), service_id UUID REFERENCES services(id), created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE sla_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), module VARCHAR(80) NOT NULL, priority VARCHAR(24) NOT NULL, max_hours INTEGER NOT NULL);
CREATE TABLE business_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rule_code VARCHAR(40) UNIQUE NOT NULL, module VARCHAR(80) NOT NULL, description TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE validation_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rule_code VARCHAR(40) UNIQUE NOT NULL, field_name VARCHAR(80) NOT NULL, expression TEXT NOT NULL, message TEXT NOT NULL);
CREATE TABLE api_clients (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), client_name VARCHAR(120) NOT NULL, scope VARCHAR(160) NOT NULL, active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL);
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(80) UNIQUE NOT NULL, description TEXT NOT NULL, resource VARCHAR(80) NOT NULL);
CREATE TABLE user_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id UUID REFERENCES citizens(id), role_id UUID REFERENCES roles(id), assigned_at TIMESTAMP NOT NULL DEFAULT now());
ALTER TABLE procedures ADD CONSTRAINT chk_procedures_status CHECK (status IN ('pendiente','en curso','en revision','observado','completado'));
ALTER TABLE notifications ADD CONSTRAINT chk_notifications_priority CHECK (priority IN ('baja','media','alta','critica'));
ALTER TABLE consents ADD CONSTRAINT chk_consents_status CHECK (status IN ('vigente','revocado','por vencer','pendiente'));
ALTER TABLE sessions ADD CONSTRAINT chk_sessions_device CHECK (length(device) >= 3);
CREATE INDEX idx_procedures_citizen_status ON procedures(citizen_id, status);
CREATE INDEX idx_notifications_citizen_read ON notifications(citizen_id, read_at);
CREATE INDEX idx_audit_events_created ON audit_events(created_at DESC);
CREATE INDEX idx_cases_status_priority ON cases(status, priority);

INSERT INTO citizens (run, full_name, email, phone, preferred_channel) VALUES ('12.345.678-9', 'Benjamin Cruzado', 'benjamin@example.local', '+56 9 0000 0000', 'email');
INSERT INTO institutions (code, name, service_level) VALUES ('REGCIVIL', 'Registro Civil', 'critico'), ('MINSEGPRES', 'MINSEGPRES', 'alto');
INSERT INTO service_categories (code, name, display_order) VALUES ('ID', 'Identidad digital', 1), ('DDU', 'Domicilio digital', 2), ('CERT', 'Certificados', 3);
INSERT INTO services (code, name, institution, available, channel) VALUES ('SVC-DDU', 'Actualizar domicilio digital', 'MINSEGPRES', true, 'web'), ('SVC-CERT', 'Solicitar certificado ciudadano', 'Registro Civil', true, 'web');
INSERT INTO procedures (citizen_id, service_id, name, status, owner) SELECT c.id, s.id, s.name, 'en curso', s.institution FROM citizens c CROSS JOIN services s WHERE c.run='12.345.678-9' LIMIT 2;
INSERT INTO procedure_steps (procedure_id, step_order, title, status, due_at) SELECT id, 1, 'Recepcion de solicitud', 'completado', current_date + 1 FROM procedures;
INSERT INTO notifications (citizen_id, procedure_id, subject, priority, channel) SELECT c.id, p.id, 'Vencimiento de tramite', 'alta', 'portal' FROM citizens c JOIN procedures p ON p.citizen_id=c.id LIMIT 1;
INSERT INTO sessions (citizen_id, device, location, active, trusted) SELECT id, 'Notebook', 'Santiago', true, true FROM citizens WHERE run='12.345.678-9';
INSERT INTO consents (citizen_id, institution, data_scope, status, expires_at) SELECT id, 'Registro Civil', 'Identidad', 'vigente', '2026-12-31' FROM citizens WHERE run='12.345.678-9';
INSERT INTO cases (citizen_id, procedure_id, status, responsible) SELECT c.id, p.id, 'en revision', 'Mesa ciudadana' FROM citizens c JOIN procedures p ON p.citizen_id=c.id LIMIT 1;
INSERT INTO digital_addresses (citizen_id, address_line, comuna, status) SELECT id, 'Avenida Demo 123', 'Santiago', 'vigente' FROM citizens WHERE run='12.345.678-9';
INSERT INTO address_history (citizen_id, address_line, source) SELECT id, 'Avenida Demo 123', 'ciudadano' FROM citizens WHERE run='12.345.678-9';
INSERT INTO notification_preferences (citizen_id, channel, quiet_hours, min_priority) SELECT id, 'email', '22:00-08:00', 'media' FROM citizens WHERE run='12.345.678-9';
INSERT INTO support_tickets (citizen_id, topic, channel, status) SELECT id, 'Clave bloqueada', 'chat', 'abierto' FROM citizens WHERE run='12.345.678-9';
INSERT INTO faq_entries (question, category, answer, helpful_count) VALUES ('Como cambio mi domicilio digital?', 'DDU', 'Ingresa a Domicilio Digital y adjunta evidencia.', 12);
INSERT INTO integration_status (service_name, status, latency_ms) VALUES ('ClaveUnica', 'operativo', 120), ('DDU', 'degradado', 650);
INSERT INTO business_rules (rule_code, module, description) VALUES ('RN-TRAMITE-001', 'procedures', 'Todo tramite debe registrar responsable y estado.'), ('RN-CONSENT-001', 'consents', 'Toda revocacion debe quedar en historial.');
INSERT INTO validation_rules (rule_code, field_name, expression, message) VALUES ('CH-RUN-001', 'run', 'not blank and format chileno', 'RUN obligatorio'), ('CH-EMAIL-001', 'email', 'contains @', 'Correo invalido');
INSERT INTO roles (code, name, description) VALUES ('CITIZEN', 'Ciudadano', 'Usuario autenticado del portal');
INSERT INTO permissions (code, description, resource) VALUES ('PROCEDURE_WRITE', 'Crear y actualizar tramites propios', 'procedures');
INSERT INTO user_roles (citizen_id, role_id) SELECT c.id, r.id FROM citizens c CROSS JOIN roles r WHERE c.run='12.345.678-9' AND r.code='CITIZEN';
INSERT INTO audit_events (citizen_id, event_type, detail) SELECT id, 'LOGIN_OK', 'Sesion inicial de datos semilla' FROM citizens WHERE run='12.345.678-9';
